[[using-images-s2i-images-java]]
= Java
{product-author}
{product-version}
:data-uri:
:icons:
:experimental:
:toc: macro
:toc-title:

toc::[]

[[s2i-images-java-overview]]
== Overview

{product-title} provides
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#source-build[S2I builder images] for building Java applications. These builder images take your application source or binary artifacts, build the source using Maven (if the source was provided), and assemble the artifacts with any required dependencies to create a new, ready-to-run image containing your Java application. This resulting image can be run on {product-title} or run directly with Docker.

The builder images are intended for use with
link:https://maven.apache.org[Maven]-based Java standalone projects that are run
via main class.


[[s2i-images-java-versions]]
== Versions

The current version of the Java S2I builder images support OpenJDK 1.8 and 11,
Jolokia 1.6.2, and Maven 3.6.


[[s2i-images-java-images]]
== Images

The RHEL 7 and RHEL 8 images are available through the Red Hat Registry:

*RHEL 7 based images*

----
$ docker pull registry.redhat.io/redhat-openjdk-18/openjdk18-openshift
$ docker pull registry.redhat.io/openjdk/openjdk-11-rhel7
----

*RHEL 8 based images*

----
$ docker pull registry.redhat.io/ubi8/openjdk-8
$ docker pull registry.redhat.io/ubi8/openjdk-11
----

ifdef::openshift-online[]
You can use the image through the `redhat-openjdk18-openshift` image stream.
endif::openshift-online[]

ifndef::openshift-online[]
To use these images on {product-title}, you can either access them directly from
the Red Hat Registry or push them into your
xref:../../install_config/registry/index.adoc#install-config-registry-overview[{product-title} container image registry].  Additionally, you can create an
xref:../../architecture/core_concepts/builds_and_image_streams.adoc#image-streams[image stream] that points to the image, either in your container image registry or at the external location. Your {product-title} resources can then reference the
link:https://github.com/jboss-openshift/application-templates/blob/master/jboss-image-streams.json[image stream definition].
endif::openshift-online[]

[[s2i-images-java-build-process]]
== Build Process
include::using_images/s2i_images/topics/build_process.adoc[]

[[s2i-images-java-configuration]]
== Configuration

By default, the Java S2I builder image uses Maven to build the project with the
following goals and options:

----
mvn -e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga -Dfabric8.skip=true --batch-mode -Djava.net.preferIPv4Stack=true -s /tmp/artifacts/configuration/settings.xml -Dmaven.repo.local=/tmp/artifacts/m2  package
----

Based on these defaults, the builder image compiles the project and copies all
the transitive dependencies into the output directory without running tests.
Additionally, if the project has a profile named `*openshift*`, then it is
activated for the build.

You can override these default goals and options by specifying the following environment variables:

.Java Environment Variables
[options="header"]
|===

|Variable name |Description

|`*MAVEN_S2I_ARTIFACT_DIRS*`
|Relative paths of source directories to scan for build output, which will be copied to $DEPLOY_DIR. Defaults to **target**.

|`*JAVA_MAIN_CLASS*`
|The main class to use as the argument to Java. This can also be specified in the *_.s2i/environment_* file as a Maven property inside the project (*docker.env.Main*).

A main class to use as argument for `java`. When this environment variable is given, all jar files in `JAVA_APP_DIR` are added to the classpath as well as `JAVA_LIB_DIR`.

|`*MAVEN_ARGS*`
|The arguments that are passed to the mvn command. Defining this replaces the defaults, which are `-e -Popenshift -DskipTests -Dcom.redhat.xpaas.repo.redhatga package`.

|`*MAVEN_ARGS_APPEND*`
|Additional Maven arguments.

|===

[[s2i-images-java-deploy-applications]]
== Building and Deploying Java Applications

ifdef::openshift-enterprise[]
[IMPORTANT]
====
The
link:https://github.com/jboss-openshift/application-templates/blob/master/jboss-image-streams.json[OpenJDK image stream] must first be installed. If you ran a standard installation, the image stream will be present.
====
endif::openshift-enterprise[]

The same S2I builder image can be used to build a Java application from source
or from binary artifacts.

[[s2i-images-java-deploy-applications-from-source]]
== Building and Deploying from Source

The Java S2I builder image can be used to build an application from source by running `oc
new-app` against a source repository:

ifdef::openshift-online[]
----
$ oc new-app redhat-openjdk18-openshift~https://github.com/jboss-openshift/openshift-quickstarts --context-dir=undertow-servlet
----
endif::openshift-online[]

ifndef::openshift-online[]
----
$ oc new-app registry.redhat.io/redhat-openjdk-18/openjdk18-openshift~https://github.com/jboss-openshift/openshift-quickstarts --context-dir=undertow-servlet
----
endif::openshift-online[]

By default, tests are not run. To build an application and run tests as part of
the build, override the default `MAVEN_ARGS`, as in the following command:

ifdef::openshift-online[]
----
$ oc new-app redhat-openjdk18-openshift~<git_repo_URL> --context-dir=<context_dir> --build-env='MAVEN_ARGS=-e -Popenshift -Dcom.redhat.xpaas.repo.redhatga package'
----
endif::openshift-online[]

ifndef::openshift-online[]
----
$ oc new-app registry.redhat.io/redhat-openjdk-18/openjdk18-openshift~<git_repo_URL> --context-dir=<context_dir> --build-env='MAVEN_ARGS=-e -Popenshift -Dcom.redhat.xpaas.repo.redhatga package'
----
endif::openshift-online[]

If a Java project consists of multiple Maven modules, it can be useful to
explicitly specify the artifact output directory.  Specifying the directory
where the Maven project outputs the artifacts enables the S2I build to pick
them up.

To specify the modules to build and the artifact output directory, use the
following command:

ifdef::openshift-online[]
----
$ oc new-app redhat-openjdk18-openshift~<git_repo_URL> --context-dir=<context_dir> --build-env='MAVEN_S2I_ARTIFACT_DIRS=relative/path/to/artifacts/dir' --build-env='MAVEN_ARGS=install -pl <groupId>:<artifactId> -am'
----
endif::openshift-online[]

ifndef::openshift-online[]
----
$ oc new-app registry.redhat.io/redhat-openjdk-18/openjdk18-openshift~<git_repo_URL> --context-dir=<context_dir> --build-env='MAVEN_S2I_ARTIFACT_DIRS=relative/path/to/artifacts/dir' --build-env='MAVEN_ARGS=install -pl <groupId>:<artifactId> -am'
----
endif::openshift-online[]

[[s2i-images-java-deploy-applications-from-binary]]
== Building and Deploying from Binary Artifacts

You can use the Java S2I builder image to build an application using binary
artifacts that you provide.

. Create a new binary build:
+
ifdef::openshift-online[]
----
$ oc new-build --name=<application_name> redhat-openjdk18-openshift --binary=true
----
endif::openshift-online[]

+
ifndef::openshift-online[]
----
$ oc new-build --name=<application_name> registry.redhat.io/redhat-openjdk-18/openjdk18-openshift --binary=true
----
endif::openshift-online[]

. Start a build and specify the path to the binary artifacts on your local machine:
+
----
$ oc start-build <application_name> --from-dir=/path/to/artifacts --follow
----

. Create an application:
+
----
$ oc new-app <application_name>
----

[[moreinfo]]
== Additional Information and Examples

- Find additional information and examples in the link:https://access.redhat.com/documentation/en-us/red_hat_jboss_middleware_for_openshift/3/html-single/red_hat_java_s2i_for_openshift/[Red Hat JBoss Middleware] documentation.
